WIP: Feature/themed logo
TeskaLabs/seacat-admin-webui pull request #12
Opened 2023-01-05 23:20 UTC by petrKavulok

Preparation work for dark themed logo. Renaming logo files.

TODO:
- [ ]  asab-webui update when https://github.com/TeskaLabs/asab-webui/pull/375 is finished
- [ ] Changelog updates

2023-05-10 16:06 UTC, Pe5h4 requested changes
@petrKavulok You need to update asab-webui submdule, also provide some pics how does it look like. Thx

2023-05-10 16:06 UTC, Pe5h4 commented on public/media/logo/.DS_Store
@petrKavulok Please, dont commit any .DS_Store files

2023-05-11 13:33 UTC, petrKavulok commented
<img width="772" alt="Screenshot 2023-05-11 at 15 30 39" src="https://github.com/TeskaLabs/seacat-admin-webui/assets/79644454/13fb87bc-2010-4c87-98ae-5bf82b8f36cb">
<img width="781" alt="Screenshot 2023-05-11 at 15 30 50" src="https://github.com/TeskaLabs/seacat-admin-webui/assets/79644454/21d8ff57-ccfa-4f37-ad64-949817631d8b">
<img width="762" alt="Screenshot 2023-05-11 at 15 31 24" src="https://github.com/TeskaLabs/seacat-admin-webui/assets/79644454/27ad9d69-4bd2-454b-b905-8bdbe824824a">

2023-05-11 15:17 UTC, Pe5h4 requested changes
@petrKavulok Update changelog and submodule with the theme logo changes

2023-05-12 07:37 UTC, Pe5h4 approved these changes

2023-05-12 07:40 UTC, merged