refactor usefieldarr to new format
TeskaLabs/seacat-admin-webui pull request #18
Opened 2023-02-02 08:31 UTC by Aringoaway

2023-02-13 17:00 UTC, Pe5h4 requested changes
Missing changelog

2023-02-13 17:00 UTC, Pe5h4 commented on src/modules/auth/clients/ClientCreateContainer.js
> +	const [incomingLink, setIncomingLink] = useState(window.location.href); // tracking method in URL
@Aringoaway 

1] you dont need to use a `useState` here since you are not changing the state anywhere else in the code

2] cant you retrieve just the pathname (since this is what you are looking for here, or not?)  from the react router dom using `location` hook?

2023-02-13 17:00 UTC, Pe5h4 commented on src/modules/auth/clients/ClientCreateContainer.js
> +			let response = await SeaCatAuthAPI.post(`/client`, refactorSubmitData(values));
@Aringoaway This is not structurally ok, its always better to declare a body and use a function for it, than to use the function as a body

```
const onSubmitNewClient = async (values) => {
	let body = refactorSubmitData(values);
	try {
		let response = await SeaCatAuthAPI.post(`/client`, body);

```
Please refactor everywhere you have it

2023-02-13 17:00 UTC, Pe5h4 commented on src/modules/auth/clients/ClientCreateContainer.js
> +			let response = await SeaCatAuthAPI.put(`/client/${client_id}`, refactorSubmitData(values));
@Aringoaway Same as above

2023-02-13 17:00 UTC, Pe5h4 commented on src/modules/auth/clients/FormFields.js
> +					<div className="ml-4">{t("ClientFormField|None")}</div>
@Aringoaway In video, you does not have it translated, but I think in code you have it. Just checking.

2023-02-14 07:30 UTC, Aringoaway commented on src/modules/auth/clients/FormFields.js
> +					<div className="ml-4">{t("ClientFormField|None")}</div>
Yes, I have it in the code, I added it after recording the video :)

2023-02-15 08:30 UTC, Pe5h4 requested changes
@Aringoaway Small inputs, otherwise good

2023-02-15 08:30 UTC, Pe5h4 commented on src/modules/auth/clients/ClientCreateContainer.js
> +	const incomingLink = useLocation(); // tracking method in URL
@Aringoaway Rename to `location`

2023-02-15 08:30 UTC, Pe5h4 commented on src/modules/auth/clients/ClientCreateContainer.js
> +		Object.keys(values).map(async (key, idx) => {
@Aringoaway Why is this mapping async, when you dont await?

2023-02-15 08:30 UTC, Pe5h4 commented on src/modules/auth/clients/ClientDetailContainer.js
> +											style={{padding: 0, borderWidth: 0, marginTop: "8px"}}
@Aringoaway If its possible, add the styling to the scss

2023-02-16 08:27 UTC, Pe5h4 requested changes

2023-02-16 08:27 UTC, Pe5h4 commented on src/modules/auth/clients/clients.scss
> +.client_secret_btn {
@Aringoaway Dont use `snake_case` for class names. Stick with the css class naming convention. Please, change it everywhere you used it.

2023-02-17 08:40 UTC, Pe5h4 approved these changes
So far so good

2023-02-17 08:40 UTC, Pe5h4 commented on src/modules/auth/clients/ClientCreateContainer.js
> +											case 'response_types': return(selectedTemplate === "Custom" && <MultiCheckbox key={key} name={key} value={value["items"]["enum"]} assignValue={client && client} setValue={setValue} disable
@Aringoaway If I were you, I would use better naming for `value` prop, since its not a single value, but an array, if I am not mistaken

2023-02-22 07:12 UTC, Aringoaway commented
@ateska Can you review pls :) ?

2023-02-22 15:10 UTC, ateska approved these changes
Nice.

2023-02-23 07:47 UTC, merged