fix: rewrite statusText check to status value
TeskaLabs/seacat-admin-webui pull request #25
Opened 2023-03-17 10:33 UTC by elpablos

close #24

2023-03-17 14:05 UTC, Pe5h4 requested changes
Thank you for your findings, I have proposed expected refactorisation in the comments

2023-03-17 14:05 UTC, Pe5h4 commented on src/modules/auth/clients/ClientCreateContainer.js
> +			if (response.status !== 200) {
@elpablos As for `get` calls, the condition should go away completely :) Meaning for this particular case:

```
let response = await SeaCatAuthAPI.get('/client/features');
setMetaData(response.data["metadata_schema"]);
setTemplate(response.data["templates"]);
```

2023-03-17 14:05 UTC, Pe5h4 commented on src/modules/auth/clients/ClientCreateContainer.js
> +			if (response.status !== 200) {
@elpablos As for `post` and `put` calls, the condition should be

```
if (response.data.result !== "OK") {
	...
}
```

2023-03-17 14:05 UTC, Pe5h4 commented on src/modules/auth/clients/ClientCreateContainer.js
> +			if (response.status !== 200) {
Please validate with @byewokko if those affected `post` and `put` endpoints returns `result`

2023-03-20 09:40 UTC, byewokko commented on src/modules/auth/clients/ClientCreateContainer.js
> +			if (response.status !== 200) {
- `POST /client/<client_id>` does **not** return `result` field
- `PUT /client/<client_id>` does return `result` field
- `DELETE /client/<client_id>` does return `result` field

2023-03-21 08:33 UTC, Pe5h4 commented on src/modules/auth/clients/ClientCreateContainer.js
> +			if (response.status !== 200) {
So, if there is no `result` for `POST` in client , then the condition is redundant and can be removed as per example in `GET`

2023-03-22 08:07 UTC, elpablos commented on src/modules/auth/clients/ClientCreateContainer.js
> +			if (response.status !== 200) {
Sorry for delay, alots of work out of seacat projects. Thanks for research.
Its already test it and check it againts seacat API impl.

2023-03-22 09:02 UTC, Pe5h4 commented on src/modules/auth/clients/ClientCreateContainer.js
> +			if (response.status !== 200) {
@elpablos No worries, thank you for your effort and for testing!

2023-03-22 09:03 UTC, Pe5h4 approved these changes
@elpablos I added changelog, all discussions are resolved, it can be merged :)

2023-03-23 09:59 UTC, merged