version bump
TeskaLabs/seacat-admin-webui pull request #48
Opened 2023-07-06 08:34 UTC by aringocode

### Changes
1. version bump
2. update Changelog

2023-07-07 04:38 UTC, aringocode commented
@Pe5h4 Can you review pls?

2023-07-07 05:14 UTC, Pe5h4 reviewed
@aringocode I thought you will use the help component in SeaCat Admin UI - meaning you will pass the URL to the https://docs.teskalabs.com/seacat-auth/

2023-07-07 05:18 UTC, aringocode commented
@Pe5h4 

> @aringocode I thought you will use the help component in SeaCat Admin UI - meaning you will pass the URL to the https://docs.teskalabs.com/seacat-auth/

I thought I would add to it when the documentation is complete

2023-07-10 12:15 UTC, Pe5h4 commented
> @Pe5h4
> 
> > @aringocode I thought you will use the help component in SeaCat Admin UI - meaning you will pass the URL to the https://docs.teskalabs.com/seacat-auth/
> 
> I thought I would add to it when the documentation is complete

@aringocode Alright then, but please stay in touch with Robin about it

2023-07-10 12:16 UTC, Pe5h4 requested changes

2023-07-10 12:16 UTC, Pe5h4 commented on CHANGELOG.md
> +- Refactor HelpComponent, remove HelpService (INDIGO Sprint 230609, [!418](https://github.com/TeskaLabs/asab-webui/pull/418))
@aringocode This should be below Refactoring section :)

2023-07-10 16:16 UTC, Pe5h4 approved these changes

2023-07-11 04:12 UTC, merged