Refactor/replace dynamic locales
TeskaLabs/seacat-admin-webui pull request #49
Opened 2023-07-06 10:19 UTC by queuing4oranges

-submodule update

2023-07-06 11:34 UTC, petrKavulok requested changes
minor changelog.md update required. Also, please, resolve conflicts before merging. Otherwise good job! :-)

2023-07-06 11:34 UTC, petrKavulok commented on CHANGELOG.md
> +### Dependencies
remove `Dependencies`. Submodule updates should go under `Features` only

2023-07-06 14:04 UTC, petrKavulok requested changes

2023-07-06 14:04 UTC, petrKavulok commented on CHANGELOG.md
> +- ASAB WebUI submodule version bump [[309a833](https://github.com/TeskaLabs/asab-webui/commit/06af558428a2106e14d00d3fdb0b9457b761f787)] commit (INDIGO Sprint 230623, [!49](https://github.com/TeskaLa
mismatch between the commit hash in URI and the short version of commit hash in square brackets

2023-07-07 05:12 UTC, Pe5h4 commented on CHANGELOG.md
> +- Submodule update - refactored dynamic locales (INDIGO Sprint 230623, [!432](https://github.com/TeskaLabs/asab-webui/pull/432))
@queuing4oranges You dont need to write here `Submodule update`.

`Refactored dynamic locales` is just fine

2023-07-10 16:23 UTC, Pe5h4 approved these changes

2023-07-12 13:39 UTC, petrKavulok approved these changes
good job 🥇

2023-07-12 13:40 UTC, merged