ClientDetailContainer Jump card
TeskaLabs/seacat-admin-webui pull request #5
Opened 2022-11-21 12:39 UTC by Aringoaway

Before:

https://user-images.githubusercontent.com/65866093/203057366-bce80a05-8b0a-40c0-8f5e-0d680bfcc91f.mp4

After:
For minimally filled-in information, the card doesn't jump. If more `Redirect URIs` is added, the card jumps and starts jumps when saving and editing.

https://user-images.githubusercontent.com/65866093/203056686-78081692-42cd-44db-a7a3-fa14cba6e41f.mp4

2022-11-21 13:27 UTC, Aringoaway commented
@Pe5h4 Can you review pls, and say what you think of these changes I showed in the video. What you think is the best way to do it?

2022-11-23 08:54 UTC, aringocode commented
@Pe5h4 I added new changes
Can you review it pls?

https://user-images.githubusercontent.com/65866093/203505424-b7d2faf8-1b65-4c71-ab5a-152e2bb9c824.mp4

2022-11-23 10:32 UTC, Pe5h4 requested changes
@Aringoaway When I see the code, it looks to me that this change has increased the complexity quite a lot and so far it does not seem to me like a appropriate structural change (sorry, my bad, I was also not sure how to do it properly, so I guess I mislead you).

I still have a feeling, that there is something not correct in the current code in main branch (the state/request/response handling) and thus it causes displaying of old values for moment. We can have a sync about it.

2022-11-24 15:21 UTC, Aringoaway commented
@Pe5h4 Can you review pls?

https://user-images.githubusercontent.com/65866093/203818805-32e09269-9f49-4e12-953d-cf70c2f98267.mp4

2022-11-24 17:01 UTC, Pe5h4 requested changes
Ok, this looks good, only minor remark

2022-11-24 17:01 UTC, Pe5h4 commented on src/modules/auth/clients/ClientDetailContainer.js
> +			setClient((prevState) => {
@Aringoaway I think you can do just:

```
setClient({...client, redirect_uris: uri})
```

2022-11-29 07:12 UTC, Aringoaway commented
@Pe5h4 Can you review again pls?

2022-11-29 08:53 UTC, Pe5h4 requested changes
Minor change

2022-11-29 08:53 UTC, Pe5h4 commented on src/modules/auth/clients/ClientDetailContainer.js
> +		setDisabled(true);
@Aringoaway Put `setDisabled(true)` between lines 92 and 93 (before `body` declaration)

2022-11-29 09:12 UTC, Pe5h4 approved these changes

2022-11-29 10:06 UTC, merged